<?php defined('BASEPATH') OR exit('No direct script access allowed.');
$config['protocol'] = 'smtp';
 $config['smtp_host'] = 'ssl://smtp.gmail.com';
// $config['smtp_host'] = 'smtp.gmail.com';
$config['smtp_timeout'] = 5;
$config['smtp_user'] = 'slife518@gmail.com';
$config['smtp_pass'] = 'jkjkjk7878';
$config['smtp_port'] = '465';
$config['newline'] = '\r\n';
// $config['mailpath'] = '/usr/sbin/sendmail';
$config['mailtype'] = 'html'; 
$config['charset'] = 'utf-8';
$config['wordwrap'] = TRUE;
